;;; ink-theme.el --- Quiet light theme for code and Chinese prose -*- lexical-binding: t; -*-

;;; Commentary:
;; Own colors and face styling here.  Fonts, spacing, mode-line contents,
;; window layout and input behavior belong to the corresponding init files.
;; Load with (load-theme 'ink t); disabling it restores the underlying faces.

;;; Code:

(deftheme ink "A quiet light theme with blue accents and readable contrast.")

(let ((bg "#FFFFFF")
      (fg "#333333")
      (surface "#F3F4F5")
      (active-surface "#ECEEF0")
      (selection "#E3ECFA")
      (inactive-selection "#ECEDEF")
      (hover "#E7E9ED")
      (accent "#245FA5")
      (muted "#747B84")
      (comment "#66717E")
      (border "#C7CBD1")
      (string "#9A4D2E")
      (green "#376B45")
      (red "#B42332")
      (amber "#895B13")
      (source "#EDF2EA")
      (source-selected "#DCE8D6"))
  (custom-theme-set-faces
   'ink
   ;; Base faces: leave font family and size to frame-setting.el.
   `(default ((t (:foreground ,fg :background ,bg))))
   '(bold ((t (:weight bold))))
   '(italic ((t (:slant italic))))
   '(bold-italic ((t (:weight bold :slant italic))))
   `(shadow ((t (:foreground ,muted))))
   `(cursor ((t (:background ,fg))))
   `(fringe ((t (:foreground ,muted :background ,bg))))
   `(region ((t (:background ,selection :extend t))))
   `(highlight ((t (:background ,hover))))
   `(hl-line ((t (:background ,surface :extend t))))
   `(link ((t (:foreground ,accent :underline t))))
   `(link-visited ((t (:foreground "#705A8C" :underline t))))
   `(minibuffer-prompt ((t (:foreground ,accent :weight bold))))
   `(success ((t (:foreground ,green :weight bold))))
   `(warning ((t (:foreground ,amber :weight bold))))
   `(error ((t (:foreground ,red :weight bold))))
   `(match ((t (:background ,selection :foreground ,accent :weight bold))))
   `(isearch ((t (:background ,accent :foreground ,bg :weight bold))))
   `(lazy-highlight ((t (:background ,selection :foreground ,fg))))
   `(isearch-fail ((t (:background "#FBE6E8" :foreground ,red))))
   `(trailing-whitespace ((t (:background "#FBE6E8"))))
   `(show-paren-match ((t (:background ,selection :foreground ,accent :weight bold))))
   `(show-paren-mismatch ((t (:background ,red :foreground ,bg :weight bold))))
   `(line-number ((t (:foreground ,muted :background ,bg))))
   `(line-number-current-line ((t (:foreground ,accent :background ,bg :weight bold))))
   `(tooltip ((t (:foreground ,fg :background ,surface))))
   `(internal-border ((t (:background ,bg))))
   `(child-frame-border ((t (:background ,border))))
   ;; Syntax: restrained colors, with comments more legible than UI metadata.
   `(font-lock-comment-face ((t (:foreground ,comment :slant italic))))
   '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
   `(font-lock-doc-face ((t (:foreground ,comment))))
   `(font-lock-string-face ((t (:foreground ,string))))
   `(font-lock-keyword-face ((t (:foreground ,accent :weight bold))))
   `(font-lock-builtin-face ((t (:foreground ,accent))))
   `(font-lock-type-face ((t (:foreground ,accent))))
   `(font-lock-constant-face ((t (:foreground ,accent))))
   `(font-lock-function-name-face ((t (:foreground ,fg :weight bold))))
   '(font-lock-function-call-face ((t (:inherit font-lock-function-name-face :weight normal))))
   `(font-lock-variable-name-face ((t (:foreground ,fg))))
   '(font-lock-variable-use-face ((t (:inherit font-lock-variable-name-face))))
   '(font-lock-warning-face ((t (:inherit warning))))
   `(font-lock-number-face ((t (:foreground ,string))))
   ;; Window chrome.  Geometry stays in frame-setting and the tab/side configs.
   `(window-divider ((t (:foreground ,border))))
   '(window-divider-first-pixel ((t (:inherit window-divider))))
   '(window-divider-last-pixel ((t (:inherit window-divider))))
   `(mode-line ((t (:background ,active-surface :foreground "#454B53"
                   :box nil :overline nil :underline nil :inverse-video nil :weight normal))))
   '(mode-line-active ((t (:inherit mode-line))))
   `(mode-line-inactive ((t (:inherit mode-line :background ,surface :foreground ,muted))))
   '(mode-line-buffer-id ((t (:weight bold))))
   `(header-line ((t (:background ,surface :foreground ,fg :box nil :overline nil :underline nil))))
   `(tab-line ((t (:inherit default :height 1.0 :box nil :background ,surface))))
   '(tab-line-tab ((t (:inherit tab-line :box nil :weight normal))))
   `(tab-line-tab-inactive ((t (:inherit tab-line-tab :foreground "#555B63" :background ,surface))))
   `(tab-line-tab-current ((t (:inherit tab-line-tab :weight bold :foreground ,accent :background ,selection))))
   `(tab-line-highlight ((t (:box nil :background ,hover :foreground ,fg))))
   `(my/tab-line-source ((t (:background ,source))))
   `(my/tab-line-source-current ((t (:background ,source-selected))))
   `(dirvish-hl-line ((t (:inherit nil :background ,selection :extend t))))
   `(dirvish-hl-line-inactive ((t (:inherit nil :background ,inactive-selection :extend t))))
   `(dired-directory ((t (:foreground ,accent :weight bold))))
   `(dired-symlink ((t (:foreground ,green))))
   '(dired-flagged ((t (:inherit error))))
   ;; Completion and Chinese input popups share the editor palette.
   `(acm-frame-default-face ((t (:foreground ,fg :background ,surface))))
   `(acm-frame-border-face ((t (:background ,border))))
   `(acm-frame-select-face ((t (:foreground ,accent :background ,selection))))
   `(rime-default-face ((t (:foreground ,fg :background ,surface))))
   `(rime-code-face ((t (:foreground ,string))))
   `(rime-cursor-face ((t (:foreground ,bg :background ,accent))))
   `(rime-highlight-candidate-face ((t (:foreground ,accent :background ,selection :weight bold))))
   `(rime-comment-face ((t (:foreground ,comment))))
   `(rime-candidate-num-face ((t (:foreground ,muted))))
   `(ido-first-match ((t (:foreground ,accent :weight bold))))
   `(ido-only-match ((t (:foreground ,green :weight bold))))
   `(ido-subdir ((t (:foreground ,accent))))
   ;; Reading and writing: preserve actual emphasis and fixed-pitch tables.
   `(outline-1 ((t (:foreground ,fg :weight bold))))
   '(outline-2 ((t (:inherit outline-1))))
   '(outline-3 ((t (:inherit outline-1))))
   '(outline-4 ((t (:inherit outline-1))))
   '(outline-5 ((t (:inherit outline-1))))
   '(outline-6 ((t (:inherit outline-1))))
   '(outline-7 ((t (:inherit outline-1))))
   '(outline-8 ((t (:inherit outline-1))))
   '(org-document-title ((t (:inherit outline-1 :height 1.15))))
   '(org-document-info ((t (:inherit shadow))))
   `(org-block ((t (:background ,surface :extend t))))
   `(org-block-begin-line ((t (:foreground ,muted :background ,surface :extend t))))
   '(org-block-end-line ((t (:inherit org-block-begin-line))))
   `(org-code ((t (:inherit fixed-pitch :foreground ,string))))
   '(org-verbatim ((t (:inherit org-code))))
   `(org-table ((t (:inherit fixed-pitch :foreground ,fg))))
   '(org-meta-line ((t (:inherit shadow))))
   '(org-special-keyword ((t (:inherit shadow))))
   '(org-tag ((t (:inherit shadow))))
   '(org-todo ((t (:inherit warning))))
   '(org-done ((t (:inherit success))))
   '(org-date ((t (:inherit link))))
   '(org-link ((t (:inherit link))))
   '(org-warning ((t (:inherit error))))
   '(org-agenda-date ((t (:inherit outline-1))))
   `(org-agenda-date-today ((t (:inherit outline-1 :foreground ,accent))))
   '(markdown-header-face ((t (:inherit outline-1))))
   `(markdown-code-face ((t (:inherit fixed-pitch :background ,surface))))
   '(markdown-inline-code-face ((t (:inherit org-code))))
   '(markdown-link-face ((t (:inherit link))))
   ;; Diffs and diagnostics should remain recognizable without vivid chrome.
   `(diff-added ((t (:foreground ,green :background "#EDF5ED" :extend t))))
   `(diff-removed ((t (:foreground ,red :background "#FBECEE" :extend t))))
   `(diff-changed ((t (:foreground ,amber :background "#FAF3E5" :extend t))))
   '(diff-header ((t (:inherit shadow))))
   '(diff-file-header ((t (:inherit outline-1))))
   `(diff-refine-added ((t (:background "#D5EAD7" :weight bold))))
   `(diff-refine-removed ((t (:background "#F2CDD2" :weight bold))))
   `(flymake-error ((t (:underline (:style wave :color ,red)))))
   `(flymake-warning ((t (:underline (:style wave :color ,amber)))))
   `(flymake-note ((t (:underline (:style wave :color ,accent)))))
   ;; Style Custom buttons through faces, never by replacing built-in code.
   `(custom-button ((t (:foreground ,fg :background ,surface :box (:line-width 1 :color ,border)))))
   `(custom-button-mouse ((t (:inherit custom-button :background ,hover))))
   `(custom-button-pressed ((t (:inherit custom-button :background ,selection))))))

(provide-theme 'ink)
;;; ink-theme.el ends here
