;;; ink-theme.el --- Quiet light theme for code and Chinese prose -*- lexical-binding: t; -*-

;;; Commentary:
;; Own colors and face styling here.  Fonts, spacing, mode-line contents,
;; window layout and input behavior belong to the corresponding init files.
;; Load with (load-theme 'ink t); disabling it restores the underlying faces.

;;; Code:

(deftheme ink "A quiet light theme with blue accents and readable contrast.")

;; Roles: neutral ink/weight expresses structure; blue identifies interaction
;; and selection; warm syntax ink distinguishes literal values.  Red/amber/green
;; are reserved for diagnostic and change states.  Comments remain darker than
;; secondary chrome; inactive selection and hover use distinct neutral surfaces.
(let ((bg "#FFFFFF")
      (fg "#333333")
      (surface "#F3F4F5")
      (selection "#E3ECFA")
      (inactive-selection "#ECEDEF")
      (hover "#E4E7EB")
      (accent "#245FA5")
      (structure "#454B53")
      (muted "#747B84")
      (comment "#66717E")
      (border "#C7CBD1")
      (section-rule "#E4E7EB")
      (string "#9A4D2E")
      (green "#376B45")
      (red "#B42332")
      (amber "#895B13"))
  (custom-theme-set-faces
   'ink
   ;; Base faces: leave font family and size to frame-setting.el.
   `(default ((t (:foreground ,fg :background ,bg))))
   '(bold ((t (:weight bold))))
   '(italic ((t (:slant italic))))
   '(bold-italic ((t (:weight bold :slant italic))))
   `(shadow ((t (:foreground ,muted))))
   `(cursor ((t (:background ,fg))))
   `(fringe ((t (:foreground ,muted :background ,bg))))
   `(region ((t (:background ,selection :extend t))))
   `(highlight ((t (:background ,hover))))
   `(hl-line ((t (:background ,surface :extend t))))
   `(link ((t (:foreground ,accent :underline t))))
   `(link-visited ((t (:foreground "#705A8C" :underline t))))
   `(minibuffer-prompt ((t (:foreground ,accent :weight bold))))
   `(success ((t (:foreground ,green :weight bold))))
   `(warning ((t (:foreground ,amber :weight bold))))
   `(error ((t (:foreground ,red :weight bold))))
   `(match ((t (:background ,selection :foreground ,accent :weight bold))))
   `(isearch ((t (:background ,accent :foreground ,bg :weight bold))))
   `(lazy-highlight ((t (:background ,selection :foreground ,fg))))
   `(isearch-fail ((t (:background "#FBE6E8" :foreground ,red))))
   `(trailing-whitespace ((t (:background "#FBE6E8"))))
   `(show-paren-match ((t (:background ,selection :foreground ,accent :weight bold))))
   `(show-paren-mismatch ((t (:background ,red :foreground ,bg :weight bold))))
   `(line-number ((t (:inherit fixed-pitch :foreground ,muted :background ,bg))))
   `(line-number-current-line ((t (:foreground ,accent :background ,bg :weight bold))))
   `(tooltip ((t (:foreground ,fg :background ,surface))))
   `(internal-border ((t (:background ,bg))))
   `(child-frame-border ((t (:background ,border))))
   ;; Syntax: restrained colors, with comments more legible than UI metadata.
   `(font-lock-comment-face ((t (:foreground ,comment :slant normal))))
   '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
   `(font-lock-doc-face ((t (:foreground ,comment))))
   `(font-lock-string-face ((t (:foreground ,string))))
   `(font-lock-keyword-face ((t (:foreground ,fg :weight bold))))
   `(font-lock-builtin-face ((t (:foreground ,structure))))
   `(font-lock-type-face ((t (:foreground ,structure))))
   `(font-lock-constant-face ((t (:foreground ,structure))))
   `(font-lock-function-name-face ((t (:foreground ,fg :weight bold))))
   '(font-lock-function-call-face ((t (:inherit font-lock-function-name-face :weight normal))))
   `(font-lock-variable-name-face ((t (:foreground ,fg))))
   '(font-lock-variable-use-face ((t (:inherit font-lock-variable-name-face))))
   '(font-lock-warning-face ((t (:inherit warning))))
   `(font-lock-number-face ((t (:foreground ,string))))
   ;; Window chrome.  Geometry stays in frame-setting and the tab/side configs.
   `(window-divider ((t (:foreground ,border))))
   '(window-divider-first-pixel ((t (:inherit window-divider))))
   '(window-divider-last-pixel ((t (:inherit window-divider))))
   `(mode-line ((t (:inherit fixed-pitch :background ,bg :foreground ,structure
                   :box nil :overline ,border :underline nil :inverse-video nil :weight normal))))
   '(mode-line-active ((t (:inherit mode-line))))
   `(mode-line-inactive ((t (:inherit mode-line :background ,bg :foreground ,muted :overline ,section-rule))))
   '(mode-line-buffer-id ((t (:weight bold))))
   `(header-line ((t (:inherit fixed-pitch :background ,surface :foreground ,fg :box nil :overline nil :underline nil))))
   ;; Page-header tabs: one continuous rule, with color marking selection.
   `(tab-line ((t (:inherit fixed-pitch :height 1.0 :box nil :weight normal
                   :overline nil :underline (:color ,section-rule :position t)
                   :foreground ,muted :background ,bg))))
   `(tab-line-tab ((t (:inherit tab-line :foreground ,structure :background ,bg
                        :underline (:color ,border :position t) :weight normal))))
   `(tab-line-tab-inactive ((t (:inherit tab-line :foreground ,muted
                                 :background ,bg :weight normal))))
   `(tab-line-tab-current ((t (:inherit tab-line-tab :weight normal
                                :foreground ,accent :background ,bg
                                :underline (:color ,accent :position t)))))
   `(tab-line-highlight ((t (:box nil :background ,bg :foreground ,accent :weight normal))))
   ;; Dependency source tabs retain a green cue without a filled rectangle.
   `(my/tab-line-source ((t (:foreground ,green :background ,bg))))
   `(my/tab-line-source-current ((t (:foreground ,green :background ,bg
                                      :underline (:color ,green :position t)))))
   `(dirvish-hl-line ((t (:inherit nil :background ,selection :extend t))))
   `(dirvish-hl-line-inactive ((t (:inherit nil :background ,inactive-selection :extend t))))
   `(dired-directory ((t (:foreground ,fg :weight bold))))
   `(dired-symlink ((t (:foreground ,green))))
   '(dired-flagged ((t (:inherit error))))
   ;; Completion and Chinese input popups share the editor palette.
   `(acm-frame-default-face ((t (:foreground ,fg :background ,surface))))
   `(acm-frame-border-face ((t (:background ,border))))
   `(acm-frame-select-face ((t (:foreground ,accent :background ,selection))))
   `(rime-default-face ((t (:foreground ,fg :background ,surface))))
   `(rime-code-face ((t (:foreground ,string))))
   `(rime-cursor-face ((t (:foreground ,bg :background ,accent))))
   `(rime-highlight-candidate-face ((t (:foreground ,accent :background ,selection :weight bold))))
   `(rime-comment-face ((t (:foreground ,comment))))
   `(rime-candidate-num-face ((t (:foreground ,muted))))
   `(ido-first-match ((t (:foreground ,accent :weight bold))))
   `(ido-only-match ((t (:foreground ,green :weight bold))))
   `(ido-subdir ((t (:foreground ,fg :weight bold))))
   ;; Reading and writing: preserve actual emphasis and fixed-pitch tables.
   `(outline-1 ((t (:foreground ,fg :weight bold))))
   '(outline-2 ((t (:inherit outline-1))))
   '(outline-3 ((t (:inherit outline-1))))
   '(outline-4 ((t (:inherit outline-1))))
   '(outline-5 ((t (:inherit outline-1))))
   '(outline-6 ((t (:inherit outline-1))))
   '(outline-7 ((t (:inherit outline-1))))
   '(outline-8 ((t (:inherit outline-1))))
   ;; Keep heading sizes local to prose faces: diff headers also use outline-1.
   `(my-writing-heading-1 ((t (:inherit my-writing-heading-font :foreground ,fg
                              :height 1.12 :overline ,section-rule :extend t))))
   `(my-writing-heading-2 ((t (:inherit my-writing-heading-font :foreground ,fg
                              :height 1.06 :overline nil))))
   `(my-writing-heading-3 ((t (:inherit my-writing-heading-font :foreground ,fg
                              :height 1.0 :overline nil))))
   `(my-writing-heading-marker ((t (:inherit fixed-pitch :foreground ,muted
                                   :weight normal :slant normal :overline nil))))
   `(my-writing-code-block ((t (:inherit fixed-pitch :foreground ,fg :background ,surface :extend t))))
   `(my-writing-inline-code ((t (:inherit fixed-pitch :foreground ,string))))
   `(my-writing-path ((t (:inherit fixed-pitch :foreground ,accent :underline t))))
   '(org-document-title ((t (:inherit my-writing-heading-font :height 1.18))))
   '(org-document-info ((t (:inherit shadow))))
   '(org-document-info-keyword ((t (:inherit shadow))))
   '(org-level-1 ((t (:inherit my-writing-heading-1))))
   '(org-level-2 ((t (:inherit my-writing-heading-2))))
   '(org-level-3 ((t (:inherit my-writing-heading-3))))
   '(org-level-4 ((t (:inherit my-writing-heading-3))))
   '(org-level-5 ((t (:inherit my-writing-heading-3))))
   '(org-level-6 ((t (:inherit my-writing-heading-3))))
   '(org-level-7 ((t (:inherit my-writing-heading-3))))
   '(org-level-8 ((t (:inherit my-writing-heading-3))))
   `(org-block ((t (:inherit fixed-pitch :background ,surface :extend t))))
   `(org-block-begin-line ((t (:inherit fixed-pitch :foreground ,muted :background ,surface :extend t))))
   '(org-block-end-line ((t (:inherit org-block-begin-line))))
   `(org-code ((t (:inherit fixed-pitch :foreground ,string))))
   '(org-verbatim ((t (:inherit org-code))))
   `(org-table ((t (:inherit fixed-pitch :foreground ,fg))))
   '(org-meta-line ((t (:inherit (fixed-pitch shadow)))))
   '(org-special-keyword ((t (:inherit (fixed-pitch shadow)))))
   '(org-tag ((t (:inherit (fixed-pitch shadow) :weight normal))))
   '(org-drawer ((t (:inherit (fixed-pitch shadow)))))
   '(org-property-value ((t (:inherit (fixed-pitch shadow)))))
   '(org-todo ((t (:inherit warning))))
   '(org-done ((t (:inherit success))))
   '(org-date ((t (:inherit link))))
   '(org-link ((t (:inherit link))))
   '(org-warning ((t (:inherit error))))
   '(org-agenda-date ((t (:inherit outline-1))))
   `(org-agenda-date-today ((t (:inherit outline-1 :foreground ,accent))))
   '(markdown-header-face ((t (:inherit my-writing-heading-font))))
   '(markdown-header-face-1 ((t (:inherit my-writing-heading-1 :height 1.0))))
   '(markdown-header-face-2 ((t (:inherit my-writing-heading-2 :height 1.0))))
   '(markdown-header-face-3 ((t (:inherit my-writing-heading-3 :height 1.0))))
   '(markdown-header-face-4 ((t (:inherit my-writing-heading-3 :height 1.0))))
   '(markdown-header-face-5 ((t (:inherit my-writing-heading-3 :height 1.0))))
   '(markdown-header-face-6 ((t (:inherit my-writing-heading-3 :height 1.0))))
   '(markdown-header-delimiter-face ((t (:inherit shadow))))
   '(markdown-header-rule-face ((t (:inherit shadow))))
   `(markdown-code-face ((t (:inherit fixed-pitch :background ,surface))))
   '(markdown-pre-face ((t (:inherit my-writing-code-block))))
   '(markdown-inline-code-face ((t (:inherit my-writing-inline-code))))
   `(markdown-table-face ((t (:inherit fixed-pitch :foreground ,fg))))
   '(markdown-language-keyword-face ((t (:inherit (fixed-pitch shadow)))))
   '(markdown-language-info-face ((t (:inherit (fixed-pitch shadow)))))
   '(markdown-metadata-key-face ((t (:inherit (fixed-pitch shadow)))))
   '(markdown-metadata-value-face ((t (:inherit (fixed-pitch shadow)))))
   '(markdown-markup-face ((t (:inherit shadow :weight normal :slant normal))))
   '(markdown-link-face ((t (:inherit link))))
   '(markdown-url-face ((t (:inherit my-writing-path))))
   '(markdown-plain-url-face ((t (:inherit my-writing-path))))
   ;; Diffs and diagnostics should remain recognizable without vivid chrome.
   `(diff-added ((t (:foreground ,green :background "#EDF5ED" :extend t))))
   `(diff-removed ((t (:foreground ,red :background "#FBECEE" :extend t))))
   `(diff-changed ((t (:foreground ,amber :background "#FAF3E5" :extend t))))
   '(diff-header ((t (:inherit shadow))))
   '(diff-file-header ((t (:inherit outline-1))))
   `(diff-refine-added ((t (:background "#D5EAD7" :weight bold))))
   `(diff-refine-removed ((t (:background "#F2CDD2" :weight bold))))
   `(flymake-error ((t (:underline (:style wave :color ,red)))))
   `(flymake-warning ((t (:underline (:style wave :color ,amber)))))
   `(flymake-note ((t (:underline (:style wave :color ,accent)))))
   `(lsp-bridge-diagnostics-error-face ((t (:underline (:style wave :color ,red)))))
   `(lsp-bridge-diagnostics-warning-face ((t (:underline (:style wave :color ,amber)))))
   `(lsp-bridge-diagnostics-info-face ((t (:underline (:style wave :color ,accent)))))
   `(lsp-bridge-diagnostics-hint-face ((t (:underline (:style wave :color ,muted)))))
   ;; Style Custom buttons through faces, never by replacing built-in code.
   `(custom-button ((t (:foreground ,fg :background ,surface :box (:line-width 1 :color ,border)))))
   `(custom-button-mouse ((t (:inherit custom-button :background ,hover))))
   `(custom-button-pressed ((t (:inherit custom-button :background ,selection))))))

(provide-theme 'ink)
;;; ink-theme.el ends here
